resolver: lts-8.5
packages:
  # hs/chat           # No package.yaml
  # hs/cs302/lab8     # No package.yaml
  # hs/dijkstra       # No package.yaml
  # hs/graph-store    # No package.yaml
  # hs/ghcjs          # Malformed package.yaml
  # hs/hsgl           # Dependency conflict from the `gl` package.
  # hs/db             # Dependency conflict from the `postgres-simple` package.
  # hs/linux-debugger # Dependency conflict with the `posix-waitpid` package.
  # hs/try-pipes      # Dependency conflict with the `pipes-bgzf` package.
  # hs/try-alex       # Type error
  # hs/record         # Type error
  # hs/opaleye        # Type error
  # hs/persistent     # Type error
  # hs/raft           # Parse error

  - hs/algo
  - hs/hiccup
  - hs/language-bash
  - hs/linenoise
  - hs/process-isolation
  - hs/nix
  - hs/learn-pricing
  - hs/smash
  - hs/try-lens
  - hs/arabic-script

extra-deps:
  - binary-generic-0.2.1
  - gnuplot-0.5.4.1
  - language-lua-0.10.0
  - record-0.4.2
  - basic-lens-0.0.2
  - data-accessor-transformers-0.2.1.7
