name: smash
version: '0.1.0.0'

executables:
  smash:
    source-dirs: .
    main:        Main.hs
    ghc-options: -O2 -funbox-strict-fields

dependencies:
  - base
  - hiccup
  - classy-prelude
  - linenoise
  - language-bash
  - bytestring

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - UnicodeSyntax
  - ViewPatterns
