name: language-bash
version: '0.6.2'
synopsis: Parsing and pretty-printing Bash shell scripts
description: ! 'A library for parsing, pretty-printing, and manipulating

  Bash shell scripts.'
category: Language
author: Kyle Raftogianis
maintainer: Kyle Raftogianis <kylerafto@gmail.com>
copyright: Copyright (c) 2013-2016 Kyle Raftogianis
license: BSD3
homepage: http://github.com/knrafto/language-bash/
git: git://github.com/knrafto/language-bash.git
bug-reports: http://github.com/knrafto/language-bash/issues
tested-with: GHC==7.6.3 GHC==7.8.4 GHC==7.10.1 GHC==7.10.2
extra-source-files:
- .gitignore
- README.md
dependencies:
- base
- parsec
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Language.Bash.Cond
  - Language.Bash.Expand
  - Language.Bash.Parse
  - Language.Bash.Parse.Word
  - Language.Bash.Pretty
  - Language.Bash.Syntax
  - Language.Bash.Word
  dependencies:
  - pretty
  - transformers
tests:
  tests:
    main: Tests.hs
    source-dirs: tests
    dependencies:
    - language-bash
    - process
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - tasty-expected-failure
