# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, lens, record }:

cabal.mkDerivation (self: {
  pname = "record-test";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ lens record ];
  meta = {
    description = "Testing out the ‘record’ library";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
