# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, contravariant, opaleye, postgresqlSimple
, productProfunctors, profunctors, semigroups, text, time
, transformers, uuid
}:

cabal.mkDerivation (self: {
  pname = "learn-opaleye";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    contravariant opaleye postgresqlSimple productProfunctors
    profunctors semigroups text time transformers uuid
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
